typography_spectrum: 0.79108
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.8853046
title: Jurate Brown
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.25
  brandColors:
    - '#002a54'
    - '#030210'
    - '#ffffff'
    - '#bc968b'
    - '#825f5d'
  lightness: 0.5
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: JurateBrown
