layout_spectrum: 0.6374245677143335
typography_spectrum: 0.9269377302844077
color:
  saturation: 0.9700479235034436
  brandStrength: 0.6449893466196954
  rhythmicContrast: 0.059305205242708325
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  lightness: 0.40692310128360987
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: JurateBrown
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Jurate Brown
purpose: []
