name: JurateBrown.com
favicon: null
layout_spectrum: 0.91053
typography_spectrum: 0.87003
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Jurate Brown
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002a54'
    - '#030210'
    - '#ffffff'
    - '#bc968b'
    - '#825f5d'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
